version: "3.9"

services:


  sniffer:
    build:
      context: .
      target: runtime
    image: network-packet-sniffer
    stdin_open: true
    tty: true
   
  test:
    build:
      context: .
      target: builder
    image: network-packet-sniffer-builder
    working_dir: /app
    command: >
      ctest --test-dir /app/build --output-on-failure
